# Generated by Django 4.0.1 on 2022-06-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=30)),
                ('restaurant_name', models.CharField(max_length=40)),
                ('food_name', models.CharField(max_length=40)),
            ],
        ),
    ]
